# Generated by Django 4.0.3 on 2022-04-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject_name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
