# Generated by Django 4.0.3 on 2022-04-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_homework_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.courses'),
        ),
    ]
