# Generated by Django 4.0.3 on 2022-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_parents_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Attendance_date',
            new_name='attendance_date',
        ),
        migrations.AddField(
            model_name='exams',
            name='remarque',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
