# Generated by Django 4.0.3 on 2022-04-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_rename_attendance_date_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kid_name1', models.CharField(max_length=255)),
                ('kid_name2', models.CharField(max_length=255)),
                ('semestre', models.CharField(max_length=255)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('mdp', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.class')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.parents')),
            ],
        ),
    ]
