# Generated by Django 4.0.3 on 2022-05-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='reclamation',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.parents')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.teachers')),
            ],
        ),
    ]
