# Generated by Django 4.0.3 on 2022-05-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_parents_kid_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RV_administration', models.IntegerField(default=0)),
                ('RV_enseignant', models.IntegerField(default=0)),
                ('NomPrenom_Ens', models.CharField(default=0, max_length=255)),
                ('Reclamation', models.IntegerField(default=0)),
                ('Titre_réclamation', models.CharField(default=0, max_length=255)),
                ('Contenue_réclamation', models.CharField(default=0, max_length=255)),
                ('Date_réclamation', models.DateField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Days_nbr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_nbr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RVenseignant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(default=0, max_length=255)),
                ('Parent_name', models.CharField(default=0, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='profile_pic',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='teachers',
            name='start_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.TextField()),
                ('session_time', models.TextField()),
                ('session_day', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.class')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('session_time', models.TextField()),
                ('num', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.class')),
                ('day_nbr_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.days_nbr')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.subjects')),
            ],
        ),
    ]
