# Generated by Django 3.1.2 on 2022-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='Deadline',
        ),
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
