# Generated by Django 3.1.2 on 2022-04-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant_app', '0002_auto_20220417_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
