# Generated by Django 3.1.2 on 2022-04-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant_app', '0004_courses_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='deadilne',
            new_name='deadline',
        ),
    ]
